name: build-app
on: [push]
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm i
      - run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_pass }}
      - uses: codacy/git-version@2.4.0
        name: Git Version
        id: setversion
        with:
          release-branch: main
          dev-branch: develop
      - name: Set stable tag
        id: setStableTag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "::set-output name=tag::c4tplatform/camino-block-explorer:stable"
          fi
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            c4tplatform/camino-block-explorer:${{github.ref_name}}-${{github.run_id}}
            c4tplatform/camino-block-explorer:${{ steps.setversion.outputs.version }}
            ${{ steps.setStableTag.outputs.tag }}
          push: true
